services:
  - type: web
    name: telegram-stair-bot
    env: python
    plan: free
    branch: main
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
